### ISSUE TITLE
Inactive window doesn't have an indicator

### ISSUE THREAD

**Issue by prateekmedia** [yeyushengfan258/Win11OS-kde#1]
As the title says, the problem lies in this file https://github.com/yeyushengfan258/Win11OS-kde/blob/main/plasma/desktoptheme/Win11OS-dark/widgets/tasks.svg.

You have not specified any indicator for bottom panel with inactive windows. 

For reference Windows 11 does this:
![Screenshot (3)](https://user-images.githubusercontent.com/41370460/126225039-a523a3a7-b5c3-446e-8644-4e59fd1f0530.png)

**Comment by yeyushengfan258** [comment]
I want to know, please ask. 
Thank you.

**Comment by prateekmedia** [comment]
@yeyushengfan258 what?

**Comment by yeyushengfan258** [comment]
My understanding is wrong, and I don't know what you want to express.

**Comment by prateekmedia** [comment]
I want to Express that the inactive window indicator is not present in your
global theme.

To reproduce this:
Open multiple windows and see the indicator of the inactive window, you
will notice that it is not there.

So it becomes impossible to detect which window is inactive.

**Comment by yeyushengfan258** [comment]
Sorry, I have no other way at the moment, because I am also studying. I will continue to improve in the future.
