### ISSUE TITLE
Cannot turn off transparency

### ISSUE THREAD

**Issue by Drakon1505** [yeyushengfan258/Win11OS-kde#15]

**Comment by unalignedcoder** [comment]
Same here. Something to do with the metadata.desktop file, where it says:

```
[AdaptiveTransparency]
enabled=true
```
Unfortunately, setting this to false makes it worse.

**Comment by unalignedcoder** [comment]
I solved this by opening in Kate the `panel-background.svg` file contained in `/.local/share/plasma/desktoptheme/Win11OS-light/solid/widgets/`.

There are several `opacity=` entries in it, that are less than 1 (`0.5`, `0.6`, `0.97` etc)

I relpaced them all with `opacity="1"` and the panel is now fully opaque.
