### ISSUE TITLE
Installing theme does not make it look like screenshots

### ISSUE THREAD

**Issue by frukbachers** [yeyushengfan258/Win11OS-kde#9]
I am not sure what to do besides install the plasma theme and choose it from the settings, but applying the global theme does not make it look like the screenshots at all.

Are you setting up configs after the fact?

**Comment by yeyushengfan258** [comment]
Could you provide a rendering of your installation?

**Comment by frukbachers** [comment]
To be honest, I have given up making it look like the screenshots. Please provide a full guide setting it up like the screenshots or don't post screenshots that are not representative of the theme at all.

**Comment by Ta180m** [comment]
@frukbachers You need to install an application launcher called [OnzeMenu 11](https://store.kde.org/p/1545530). Then the theme looks exactly like the screenshots after selecting this launcher in the `Show Alternatives...`.
